In [80]:
import pandas as pd
import numpy as np

In [81]:
df = pd.read_csv('Bollywood-Songs-Dataset(2017-23).csv')

In [82]:
df.head()

music_name                       singer  release  \
0  Ek Haseena Thi Ek Deewana Tha                 Yasser Desai     2017   
1                    Hue Bechain  Palak Muchhal, Yasser Desai     2017   
2                  Hanste Hanste  Palak Muchhal, Yasser Desai     2017   
3                           Nain  Palak Muchhal, Yasser Desai     2017   
4           Aankhon Mein Aansoon  Palak Muchhal, Yasser Desai     2017   

                                              lyrics  \
0  Ek haseena thi ek deewana tha Kya kahun tumse ...   
1  Hue bechain pehli bar hmny raaz ye jana Mohabb...   
2  Hanste hanste ro diye tum Kis mushkil mein kho...   
3  Kuchh sawaal pyar ke lab pe hai ruke ruke Jaad...   
4  Aankhon mein aansoo leke hoton se muskuraye Aa...   

                                          thumbnail  
0  https://i.ytimg.com/vi/6obiArkHwAk/hqdefault.jpg  
1  https://i.ytimg.com/vi/6obiArkHwAk/hqdefault.jpg  
2  https://i.ytimg.com/vi/rVKX19fNV0A/hqdefault.jpg  
3  https://i.ytimg.com/vi/ZHbbcy7u9Rk/hqdefault.jpg  
4  https://i.ytimg.com/vi/izP81UySf0Y/hqdefault.jpg

In [83]:
music = df.copy()

# Preprocessing

In [84]:
music.isnull().sum()

music_name    0
singer        0
release       0
lyrics        0
thumbnail     0
dtype: int64

In [85]:
music.duplicated().sum()

0

In [86]:
music['singer'] = music['singer'].apply(
    lambda x: " ".join(name.replace(" ", "").lower() for name in x.split(","))
)


In [87]:
music['lyrics'] = music['lyrics'].apply(lambda x: x.lower())

In [88]:
music.head()

music_name                    singer  release  \
0  Ek Haseena Thi Ek Deewana Tha               yasserdesai     2017   
1                    Hue Bechain  palakmuchhal yasserdesai     2017   
2                  Hanste Hanste  palakmuchhal yasserdesai     2017   
3                           Nain  palakmuchhal yasserdesai     2017   
4           Aankhon Mein Aansoon  palakmuchhal yasserdesai     2017   

                                              lyrics  \
0  ek haseena thi ek deewana tha kya kahun tumse ...   
1  hue bechain pehli bar hmny raaz ye jana mohabb...   
2  hanste hanste ro diye tum kis mushkil mein kho...   
3  kuchh sawaal pyar ke lab pe hai ruke ruke jaad...   
4  aankhon mein aansoo leke hoton se muskuraye aa...   

                                          thumbnail  
0  https://i.ytimg.com/vi/6obiArkHwAk/hqdefault.jpg  
1  https://i.ytimg.com/vi/6obiArkHwAk/hqdefault.jpg  
2  https://i.ytimg.com/vi/rVKX19fNV0A/hqdefault.jpg  
3  https://i.ytimg.com/vi/ZHbbcy7u9Rk/hqdefault.jpg  
4  https://i.ytimg.com/vi/izP81UySf0Y/hqdefault.jpg

In [89]:
music['release'] = music['release'].astype(str)

In [90]:
music['tags'] = music["singer"] + " " + music["release"] + " " + music["lyrics"]

In [91]:
music.head()

music_name                    singer release  \
0  Ek Haseena Thi Ek Deewana Tha               yasserdesai    2017   
1                    Hue Bechain  palakmuchhal yasserdesai    2017   
2                  Hanste Hanste  palakmuchhal yasserdesai    2017   
3                           Nain  palakmuchhal yasserdesai    2017   
4           Aankhon Mein Aansoon  palakmuchhal yasserdesai    2017   

                                              lyrics  \
0  ek haseena thi ek deewana tha kya kahun tumse ...   
1  hue bechain pehli bar hmny raaz ye jana mohabb...   
2  hanste hanste ro diye tum kis mushkil mein kho...   
3  kuchh sawaal pyar ke lab pe hai ruke ruke jaad...   
4  aankhon mein aansoo leke hoton se muskuraye aa...   

                                          thumbnail  \
0  https://i.ytimg.com/vi/6obiArkHwAk/hqdefault.jpg   
1  https://i.ytimg.com/vi/6obiArkHwAk/hqdefault.jpg   
2  https://i.ytimg.com/vi/rVKX19fNV0A/hqdefault.jpg   
3  https://i.ytimg.com/vi/ZHbbcy7u9Rk/hqdefault.jpg   
4  https://i.ytimg.com/vi/izP81UySf0Y/hqdefault.jpg   

                                                tags  
0  yasserdesai 2017 ek haseena thi ek deewana tha...  
1  palakmuchhal yasserdesai 2017 hue bechain pehl...  
2  palakmuchhal yasserdesai 2017 hanste hanste ro...  
3  palakmuchhal yasserdesai 2017 kuchh sawaal pya...  
4  palakmuchhal yasserdesai 2017 aankhon mein aan...

In [92]:
dataset = music[['music_name', 'tags', 'thumbnail']]

In [93]:
dataset['music_name'][23]

'Main Hoon Saath Tere'

# TF-IDF Vectorization 

In [94]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer(max_features=5000)

In [95]:
vectors = tf.fit_transform(dataset['tags']).toarray()

In [96]:
vectors

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [97]:
tf.get_feature_names_out()[1:100]

array(['100', '12', '2017', '2018', '2019', '2020', '2021', '2022',
       '2023', '3g', 'aa', 'aaa', 'aab', 'aabaad', 'aadat', 'aadha',
       'aadhe', 'aadhi', 'aafat', 'aag', 'aaga', 'aage', 'aagey', 'aah',
       'aaha', 'aahe', 'aahista', 'aaho', 'aahon', 'aai', 'aaina',
       'aaine', 'aaiyaan', 'aaiyan', 'aaj', 'aaja', 'aajo',
       'aakankshasharma', 'aakar', 'aake', 'aakhan', 'aakhir', 'aakhiri',
       'aakhri', 'aala', 'aam', 'aan', 'aana', 'aanch', 'aanchal',
       'aandhi', 'aandhiyaan', 'aandhiyan', 'aane', 'aanewale', 'aangan',
       'aankh', 'aankhe', 'aankhein', 'aankhen', 'aankho', 'aankhon',
       'aansoo', 'aansu', 'aao', 'aaogey', 'aap', 'aapa', 'aapan', 'aape',
       'aapna', 'aapne', 'aapni', 'aaram', 'aare', 'aarzoo', 'aarzuon',
       'aas', 'aasaan', 'aashiq', 'aashiqaan', 'aashiqan', 'aashiqe',
       'aashiqui', 'aasmaa', 'aasmaan', 'aasmaano', 'aasman', 'aasmani',
       'aata', 'aate', 'aath', 'aathe', 'aati', 'aaun', 'aaunga', 'aave',
       'aavjo'

# Calculating similarity between vectors

In [98]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vectors)

In [99]:
similarity

array([[1.00000000e+00, 2.74861232e-02, 1.82898742e-01, ...,
        3.49259134e-02, 0.00000000e+00, 5.34304837e-02],
       [2.74861232e-02, 1.00000000e+00, 4.79905817e-02, ...,
        7.67723124e-02, 1.59507661e-03, 3.13621743e-02],
       [1.82898742e-01, 4.79905817e-02, 1.00000000e+00, ...,
        7.07926923e-02, 4.46814060e-04, 7.44447085e-02],
       ...,
       [3.49259134e-02, 7.67723124e-02, 7.07926923e-02, ...,
        1.00000000e+00, 4.88178898e-03, 4.17590362e-02],
       [0.00000000e+00, 1.59507661e-03, 4.46814060e-04, ...,
        4.88178898e-03, 1.00000000e+00, 8.29833009e-04],
       [5.34304837e-02, 3.13621743e-02, 7.44447085e-02, ...,
        4.17590362e-02, 8.29833009e-04, 1.00000000e+00]])

In [100]:
similarity

array([[1.00000000e+00, 2.74861232e-02, 1.82898742e-01, ...,
        3.49259134e-02, 0.00000000e+00, 5.34304837e-02],
       [2.74861232e-02, 1.00000000e+00, 4.79905817e-02, ...,
        7.67723124e-02, 1.59507661e-03, 3.13621743e-02],
       [1.82898742e-01, 4.79905817e-02, 1.00000000e+00, ...,
        7.07926923e-02, 4.46814060e-04, 7.44447085e-02],
       ...,
       [3.49259134e-02, 7.67723124e-02, 7.07926923e-02, ...,
        1.00000000e+00, 4.88178898e-03, 4.17590362e-02],
       [0.00000000e+00, 1.59507661e-03, 4.46814060e-04, ...,
        4.88178898e-03, 1.00000000e+00, 8.29833009e-04],
       [5.34304837e-02, 3.13621743e-02, 7.44447085e-02, ...,
        4.17590362e-02, 8.29833009e-04, 1.00000000e+00]])

# Recommender Function 

In [101]:
dataset[dataset['music_name']== 'Hanste Hanste'].index[0]

2

In [102]:
def recommend(song):
    song_index = dataset[dataset['music_name']== song ].index[0]
    distances = similarity[song_index]
    song_list = sorted(list(enumerate(distances)), reverse=True, key = lambda x: x[1])[1:6]

    for i in song_list:
        print(dataset.iloc[i[0]].music_name)


In [103]:
recommend('Tera Fitoor')

Ishq Ishq Tera
Aaj Se Teri
Phir Aur Kya Chahiye
Sab Jhulas Gaya
Pagal Hai Mera Dil


# saving the dataset and similarity matrix  for streamlit 

In [104]:
import joblib

In [105]:
joblib.dump(dataset, "dataset.pkl")

['dataset.pkl']

In [107]:
joblib.dump(similarity, "similarity.pkl")

['similarity.pkl']